### ISSUE TITLE
New Mac OS dmg (1.13.0)

### ISSUE THREAD

**Issue by ryanpcmcquen** [ytmdesktop/ytmdesktop#409]
I built it locally after checking out the `v1.13.0` tag:

https://filebin.net/woo8rg0gqkm31skd

**Comment by ryanpcmcquen** [comment]
@adlerluiz, new Mac OS package here.

**Comment by ryanpcmcquen** [comment]
Backup link:
https://ufile.io/hnsmxbiv

**Comment by adlerluiz** [comment]
thank you very much, I'm downloading and I will make available, on dist folder latest-mac.yml file is generated, could you send it too?

**Comment by ryanpcmcquen** [comment]
@adlerluiz:
```
version: 1.13.0
files:
  - url: YouTube-Music-Desktop-App-1.13.0.dmg
    sha512: RNaP5u7uf6yOzlND0NV5hLJzgabkgtlWMMV4kanf5RMH0xj6NLwLXd6U82SNXoFgixdRNHjcAQ7CWTYtKr1VlQ==
    size: 90523056
path: YouTube-Music-Desktop-App-1.13.0.dmg
sha512: RNaP5u7uf6yOzlND0NV5hLJzgabkgtlWMMV4kanf5RMH0xj6NLwLXd6U82SNXoFgixdRNHjcAQ7CWTYtKr1VlQ==
releaseDate: '2020-09-24T23:36:39.647Z'
```
