### ISSUE TITLE
Main screen and play screen looks bad.

### ISSUE THREAD

**Issue by Andret2344** [ytmdesktop/ytmdesktop#548]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
Well... It seems like some CSS didn't apply correctly. Main screen and play screen are malformed. 

Bug **sometimes** doesn't appear when installed app manually via exe installer, but it's present when installed via choco or manually changed manifest file in winget.

**To Reproduce**
Make sure to completely uninstall whole app and remove all its data (suggested tool to do so: Revo uninstaller).

Scenario I
1. Install choco if not haing already (https://chocolatey.org/install)
2. `choco install ytmdesktop` with elevated rights on any cmd-like terminal.
3. Run the app (pass throught the login).

Scenario II.
1. Install winget (https://github.com/microsoft/winget-cli)
2. Clone winget dpkg repo from git (https://github.com/microsoft/winget-pkgs)
3. In cloned repository go to ./manifests/YTMDesktop/YTMDesktop
4. Change the only yml file into correct for latest version.
```
Installers:
  - Arch: x64
    Url: https://github.com/ytmdesktop/ytmdesktop/releases/download/v1.13.0/YouTube-Music-Desktop-App-Setup-1.13.0.exe
    Sha256: 1e76442d40b273e42b5068972ccf0129c81b75a64bb26a0ef086ca7f6850285d
```
5. In this folder, execute `winget validate <file>.yml` using the file name to validate its correctness
6. Execute `winget install -m <file>.yml` to install the app from manifest.
7. Run the app (pass throught the login).

**Expected behavior**
It looks ok

**Screenshots**
![image](https://user-images.githubusercontent.com/40674613/103140387-55276680-46e6-11eb-8516-eed7affd9d99.png)
![image](https://user-images.githubusercontent.com/40674613/103140394-6c665400-46e6-11eb-87f3-74a0ddb4a37b.png)

**Environment (please complete the following information):**
 * YTMDesktop version: ***1.13.0***
 * OS: ***Windows***
 * OS version: ***10.0.19042 Home***
 * Arch: ***x64***
* Installation way: ***Described in reproduction steps as causing problem***
