### ISSUE TITLE
SUGGESTION: increase album cover size

### ISSUE THREAD

**Issue by MetalJR** [ytmdesktop/ytmdesktop#726]
would love to see the album cover larger on the now playing screen.  There's lots of real estate entirely unused

**Comment by Alipoodle** [comment]
This is something which would not be implemented into the application.
You can edit this yourself by creating some Custom CSS and importing it into the Application to change the size of the Album Art in this page.

I personally have made the Album art in the bottom and the Queue larger myself.
```css
ytmusic-player-queue-item.style-scope.ytmusic-player-queue {
    --ytmusic-player-queue-item-thumbnail-size: 50px !important;
}
```
This is the code for the Queue

Some guides on learning CSS:
https://www.codecademy.com/learn/learn-css
https://www.w3schools.com/css/
